= Spring Basics
:toclevels: 4
:imagesdir: ./images

The purpose of this training is to get you familiar with the basic functions of Spring as well as to show you why they are useful.

In order to help you see why Spring is useful, the first part of the training focuses on some important design patterns instead of diving straight into Spring.

This training assumes you are able to write code in Java.

== How does this training work?

The training organization is as following:

- First a bit of theory explaining the concepts, principles,
  practices and conventions.
  Then a lab to bring the theory to practise
- Each lab is self-contained,
  but continues on the knowledge you gained in previous labs
- Labs contain additional practical information which you
  need to be able to do the lab exercises
- Labs often contain references to resources.
  These resources provide you with more in-depth information on how things work,
  and you can most probably not do the exercises without reading through the
  resources. So, use the resources!
- Each lab explains where you can find the files for the lab.
  All lab files are structured inside the `labs` directory
- For each lab where you need to create/adjust files,
  there is a sample solution available.
  You can find the solutions in the `solutions` directory.

WARNING: The solutions are provided to give you an idea how
  you _could have_ implement the exercise. +
  It's good to look at them,
  _after_ you implemented the exercise yourself. +
  Peeking at the solution _before_ you finished the exercise *is not recommended*. +
  https://www.wanderlustworker.com/the-importance-of-failure-5-valuable-lessons-from-failing/[Learning is in the failing until you succeed]


//== Introduction
include::./2-introduction.adoc[leveloffset=+1]

//== First In-Depth Chapter
include::./3-dependency-injection.adoc[leveloffset=+1]

include::./4-spring-application-context.adoc[leveloffset=+1]

include::./5-java-annotations.adoc[leveloffset=+1]

include::./6-web-services.adoc[leveloffset=+1]

include::./7-jdbc.adoc[leveloffset=+1]


//== Appendix
//include::./appendix/install-sdkman.adoc[leveloffset=+1]
